version: "3.9"
services:
  db:
    image: postgres:15-alpine
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=psychobot
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  backend:
    build: ./backend
    env_file:
      - ./.env
      - ./.env.example
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - JWT_SECRET_KEY=${JWT_SECRET_KEY}
      - JWT_EXPIRE_MINUTES=${JWT_EXPIRE_MINUTES}
      - ADMIN_EMAIL=${ADMIN_EMAIL}
      - ADMIN_PASSWORD=${ADMIN_PASSWORD}
      - TELEGRAM_BOT_TOKEN=${TELEGRAM_BOT_TOKEN}
      - BOT_INTERNAL_TOKEN=${BOT_INTERNAL_TOKEN}
      - TZ=${TZ}
    depends_on:
      - db
    ports:
      - "8000:8000"

  bot:
    build: ./bot
    env_file:
      - ./.env
      - ./.env.example
    environment:
      - TELEGRAM_BOT_TOKEN=${TELEGRAM_BOT_TOKEN}
      - NEXT_PUBLIC_API_URL=${NEXT_PUBLIC_API_URL}
      - BOT_INTERNAL_TOKEN=${BOT_INTERNAL_TOKEN}
      - TZ=${TZ}
    depends_on:
      - backend

  web:
    build: ./web
    env_file:
      - ./.env
      - ./.env.example
    environment:
      - NEXT_PUBLIC_API_URL=${NEXT_PUBLIC_API_URL}
    ports:
      - "3000:3000"
    depends_on:
      - backend

volumes:
  db_data:
